apiVersion: apps/v1
kind: Deployment
metadata:
  name: lead-scoring-api
spec:
  replicas: 3  # Number of replicas for load balancing
  selector:
    matchLabels:
      app: lead-scoring-api
  template:
    metadata:
      labels:
        app: lead-scoring-api
    spec:
      containers:
      - name: lead-scoring-api
        image: your-username/lead-scoring-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1024Mi"
            cpu: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  name: lead-scoring-service
spec:
  selector:
    app: lead-scoring-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
